WIP - change how getting tags

diff --git a/.github/workflows/stage-release.yml b/.github/workflows/stage-release.yml
--- a/.github/workflows/stage-release.yml
+++ b/.github/workflows/stage-release.yml
@@ -16,8 +16,6 @@ jobs:
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
-        with:
-          fetch-tags: true
       - name: Extract version from branch name
         id: extract_version
         run: |
@@ -47,7 +45,8 @@ jobs:
           git push origin selenium-${{ env.VERSION }}
       - name: Remove Nightly Tag
         run: |
-          git tag -d nightly
+          git fetch --tags
+          git tag -d nightly || echo "Nightly tag not found"
           git push origin :refs/tags/nightly
       - name: "Release"
         uses: softprops/action-gh-release@v2
